#!/usr/bin/env bash
set -euo pipefail

export CAMERA_INDEX="${CAMERA_INDEX:-0}"
export CAMERA_WIDTH="${CAMERA_WIDTH:-640}"
export CAMERA_HEIGHT="${CAMERA_HEIGHT:-480}"
export CAMERA_FPS="${CAMERA_FPS:-8}"
export MJPEG_FPS="${MJPEG_FPS:-6}"
export CAMERA_JPEG_QUALITY="${CAMERA_JPEG_QUALITY:-65}"
export AUDIO_IN_ENABLED="${AUDIO_IN_ENABLED:-false}"
export VISION_ENABLED="${VISION_ENABLED:-true}"
export AUTO_VISION_ENABLED="${AUTO_VISION_ENABLED:-true}"
export AUTO_VISION_INTERVAL_S="${AUTO_VISION_INTERVAL_S:-10}"
export VISION_IMAGE_MAX_WIDTH="${VISION_IMAGE_MAX_WIDTH:-640}"
export VISION_JPEG_QUALITY="${VISION_JPEG_QUALITY:-85}"

exec "$(dirname "${BASH_SOURCE[0]}")/_run_profile.sh"
